### ISSUE TITLE
How can I logon by SmardCard?

### ISSUE THREAD

**Issue by Peymanmi** [phaetto/windows-credentials-provider#10]
Hi, It's just a question no bug report.

I need to create custom provider which login by SmartCard.

I already checked https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credpackauthenticationbuffera and call CredMArshalCredential but sill have problem.

Thanks in advance.

**Comment by Peymanmi** [comment]
Hi, It's just a question no bug report.

I need to create custom provider which login by SmartCard. 

I already checked https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credpackauthenticationbuffera and call [CredMArshalCredential ](https://docs.microsoft.com/en-gb/windows/win32/api/wincred/nf-wincred-credmarshalcredentiala)but sill have problem.

Thanks in advance.

**Comment by phaetto** [comment]
Hey Peymanmi,

I am not sure I can help you with that - you might have better luck googling it.

Maybe the following article at code project will get you started:
[A-Smart-Card-Framework-for-NET](https://www.codeproject.com/Articles/16653/A-Smart-Card-Framework-for-NET)

Good luck!
