### ISSUE TITLE
Is the Credential Provider have to use the Windows password?

### ISSUE THREAD

**Issue by trac3me** [phaetto/windows-credentials-provider#11]
Hello there, great product:
I am using CredentialProvider to develop my custom login method，After my research，the Credential Provider seems to require the user's original Windows password.  my question is : Is the Credential Provider have to know the original Windows password, and pass it to the operating system for verification, Otherwise the user cannot log in successfully?

**Comment by phaetto** [comment]
The Credentials Provider does connect your credentials with a user where that computer can verify it. Eventually this means matching a username with password (for the default security provider)

If you want to create a custom login method, you will have to generate your own username/password and link it to some kind of artifact that is been used for your login method (e.g. USB device, certificate, etc)

If you want to do this properly you might have to create an SSP. Take a look at the following links:
 https://docs.microsoft.com/en-us/windows/win32/secauthn/authentication-functions
https://docs.microsoft.com/en-us/windows/win32/secauthn/writing-and-installing-a-security-support-provider

**Comment by trac3me** [comment]
Thank you very much. I will read these two texts immediately to see what SSP is .
