### ISSUE TITLE
Issue with logon

### ISSUE THREAD

**Issue by graudouin** [phaetto/windows-credentials-provider#13]
Hi there,
I have rebuilt this project in VS2015. I have also merged the registry. When I log out and in again, Windows 10 still shows the standard logon screen without any options. How do I get the custom login screen to show?
Thank in advance

**Comment by phaetto** [comment]
I haven't tried building with 2015.

Sounds like you need to register the COM component dll manually if it is not registered. Check this tool for more details:
https://docs.microsoft.com/en-us/dotnet/framework/tools/regasm-exe-assembly-registration-tool
