### ISSUE TITLE
Question: Release Credential Provider without reboot

### ISSUE THREAD

**Issue by martijnvanschie** [phaetto/windows-credentials-provider#14]
Hi,

Great to find a good extended example for Credential Providers. The info only is not always easy to find.

We are working on developing a custom credential provider. To test it we register the component for COM interop and add the regkey so it is show in CredUI. 

Problem is that when we want to test the actual login the component is kept in use (by WinLogin probably) and builds for do not succeed as the file is in use. Is there way to free the component without unregistering and rebooting.

**Comment by wikiyu** [comment]
The easiest way is to build without registering component. And as afterbuild action make an "copy to other place and register". 

Also check if you are really making a good work at dispatch/exit of logon process with clearing everything so LogonUI is not working in background so you can make a change of library when system is working. You should not have an "LogonUI" in TaskManager after login.

**Comment by martijnvanschie** [comment]
Thanx for the quick reply.

I feel that the copy will still fail as the dll is in use but i will check that. Also cleanup could be the reason for keeping the file in use. I will also need the check our code for any uncleaned references.

**Comment by martijnvanschie** [comment]
The "In Use" issues is not occurring anymore. Dunno how i fix it but i'm happy :)
