### ISSUE TITLE
Building and running the project

### ISSUE THREAD

**Issue by isrishu** [phaetto/windows-credentials-provider#16]
Hello Pheatto/Alexander
Nice article. But, mine is not an issue
I have considerable experience in C# but have never worked on a credentials provider.
And it has been some time since my last C# app after having shifted to mobile app development. So, I need your help to build and run this code on my computer for a project I need to work on.
Which code/project should I run? Or is just build and get a DLL and run from somewhere? 
I know my request sounds kind of trivial but can you help me? I will be very thankful to you for this.

Best
Srishu

**Comment by phaetto** [comment]
Hey,

Sorry, but I don't have the time to help on this one.

Good luck!
