### ISSUE TITLE
Could your example be used for a Pre-Logon Access Provider using CPUS_PLAP as usage scenario?

### ISSUE THREAD

**Issue by gitnewcomer** [phaetto/windows-credentials-provider#19]
Hi @phaetto, I was searching for a Pre-Logon Access Provider for OpenVPN, but did not found any and there isn't any example for this kind of provider. :(
On the OpenVPN GUI Client (https://github.com/OpenVPN/openvpn-gui/issues/77#issuecomment-887409666) it seems that nobody knows how to implement this. Could you give them some hints how they cold do it? Thanks! :)

**Comment by phaetto** [comment]
Hey @gitnewcomer, I just read your comment on that thread, and I can say that it is a very good explanation on what someone needs to do in order to enable that.

Is there something else that you would need from me?
