### ISSUE TITLE
Login without clicking on the user.

### ISSUE THREAD

**Issue by hans-ahrens** [phaetto/windows-credentials-provider#2]
Dear Phaetto,

Our goal is to login a user once we receive the user data via an NFC card.
If i see your code its possible to write the data to the registry and then use it. 
But i cant find a way to use it without first going to the user icon.  

Is there a way to trigger login once we received the user data ? 

Best Regards,
Hans

**Comment by phaetto** [comment]
@hans-ahrens Hey Hans, since this seems to be a particularly common request I will try to provide an example on auto-login using an external event.

**Comment by hans-ahrens** [comment]
@phaetto Thank you for this. Looking forward to see the example.

**Comment by phaetto** [comment]
@hans-ahrens I have just now pushed the PR #4 regarding a example with a timer based background login request that switches to autologin.

Can you check out the branch and let me know if this example works for you?
