### ISSUE TITLE
Is it possible to implement CPUS_CHANGE_PASSWORD scenario in credential provider c#

### ISSUE THREAD

**Issue by arjunpv0** [phaetto/windows-credentials-provider#20]
Hi phaetto,
Is it possible to implement password change scenario in c#, because I couldn't find any doc or sample on implementing the same in c#.
In c++, Kerb_changepassword_request can be used by packing the credentials in getserialization function, but in c#, I couldn't find any method for packing the credentials.

**Comment by phaetto** [comment]
Hey @arjunpv0,

Yeah it is definitely possible. I have made the kerberos packing, but it is on another project and I have not open sourced it yet.

You can find the details in [pgina project](https://github.com/pgina/pgina) similar implementation in C++.

**Comment by arjunpv0** [comment]
Thank you for your confirmation @phaetto .
