### ISSUE TITLE
windows 2012 support

### ISSUE THREAD

**Issue by nikhilty** [phaetto/windows-credentials-provider#22]
hey, recently i tried testing this code on window server 12 with some changes. Like i added CPFT_EDIT_TEXT to get username and CPFT_PASSWORD_TEXT to get the password. This works fine on windows 11, 16 and 19 but on windows 2012 the CPFT_EDIT_TEXT isn't shown at all. any idea what am i missing here?  Below is a snapshot from my WindowsCredentialProviderTile file 

```
public List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> CredentialProviderFieldDescriptorList = new List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> {
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SMALL_TEXT,
                dwFieldID = 1,
                pszLabel = "Hello World",
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_EDIT_TEXT,
                dwFieldID = 2,
                pszLabel = "Username",
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_PASSWORD_TEXT,
                dwFieldID = 3,
                pszLabel = "Password",
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SUBMIT_BUTTON,
                dwFieldID = 4,
                pszLabel = "Login",
            }
        };
```

**Comment by phaetto** [comment]
Hey @nikhilty,

Is that the only field that is not shown?
Maybe you should try rebuilding the project, it might be an update problem.

**Comment by nikhilty** [comment]
i did try. it does work on windows 2016, 2019 and 2011 but on 2012 it doesn't show up at all

**Comment by phaetto** [comment]
Just to clarify, is it only the text input field that is not visible? The rest of the elements are there?

**Comment by nikhilty** [comment]
yeah its only the `CPFT_EDIT_TEXT` field which isn't visible on 2012. rest are fine

**Comment by nikhilty** [comment]
Also the `CPFT_SUBMIT_BUTTON` isn't shown. 

Only `CPFT_TILE_IMAGE`, `CPFT_SMALL_TEXT` and `CPFT_PASSWORD_TEXT` is shown

**Comment by phaetto** [comment]
That could be the COM bindings for that specific windows version. I cannot find any documentation for it, so it is very hard to find out.
I would check the COM definitions in the SDK for your version.

**Comment by nikhilty** [comment]
ok so i figured it out. On windows 2012 it isn't allowed to switch users on lock screen so adding an editable USERNAME field wasn't being allowed although i am able to add a `CPFT_SMALL_TEXT` or `CPFT_LARGE_TEXT` USERNAME field. 

Closing this ticket.

**Comment by nikhilty** [comment]
Hey @phaetto , one more issue i'm seeing with **windows 2012 r1 standard** server is that the `ICredentialProvider::GetFieldDescriptorAt` method isn't getting called at logon which is causing a blank logon screen with fields not getting populated. All other methods under `ICredentialProvider` are getting called. 

The same plugin is working fine with **windows 2012 r1 and r2 datacenter servers** as well as **2012 r2 standard server**. 

snapshot of the GetFieldDescriptorAt method 
```
public int GetFieldDescriptorAt(uint dwIndex, [Out] IntPtr ppcpfd) 
        {
            Log.LogMethodCall();
            if (dwIndex >= credentialTile.CredentialProviderFieldDescriptorList.Count)
            {
                return HResultValues.E_INVALIDARG;
            }

            var listItem = credentialTile.CredentialProviderFieldDescriptorList[(int) dwIndex];
            var pcpfd = Marshal.AllocCoTaskMem(Marshal.SizeOf(listItem)); 
            Marshal.StructureToPtr(listItem, pcpfd, false); 
            Marshal.StructureToPtr(pcpfd, ppcpfd, false); 

            return HResultValues.S_OK;
}
```

**Comment by phaetto** [comment]
Sorry, I don't have the testing environment to check this out, I hope someone else can help

**Comment by nikhilty** [comment]
i was able to do this. thanks
