### ISSUE TITLE
Password reset in custom credential provider

### ISSUE THREAD

**Issue by nikhilty** [phaetto/windows-credentials-provider#26]
Hey how can i support password reset in the custom credential provider i have built which overrides the login screen?

**Comment by phaetto** [comment]
You need to support _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_CHANGE_PASSWORD
https://github.com/phaetto/windows-credentials-provider/blob/dd3f5bbe86f1cf1f8f679ac109332975fbf3373c/WindowsCredentialProviderTest/TestWindowsCredentialProvider.cs#L36

**Comment by nikhilty** [comment]
i did try that and added the necessary code in `GetSerialization` when usage scenario is `CPUS_CHANGE_PASSWORD`. But my question is when im on login page and enter my username and password, it shows `password expired` and asks to reset the password, when i click ok it just errors out and comes back to login screen instead of asking to reset password. 

How do i implement the password reset UI to allow the user to enter newpassword etc? please help

**Comment by nikhilty** [comment]
@phaetto any ideas?

**Comment by phaetto** [comment]
This is the similar to this one: #27 

You will need to port the serialization for kerberos to do that. In this example repo this is not implemented.
You can find more details on the implementation here:
https://github.com/pgina/pgina/blob/f7cf2a074cf00432aa619478cedd8181b31f1680/pGina/src/CredentialProvider/SerializationHelpers.cpp#L103
