### ISSUE TITLE
[Help Wanted - Serialize Remote Credential ]

### ISSUE THREAD

**Issue by subu1979** [phaetto/windows-credentials-provider#27]
This is where we receive credential through RDP

public int UpdateRemoteCredential(ref _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION pcpcsIn, out _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION pcpcsOut)
        {
            ShowInfo showInfo = new ShowInfo();
            showInfo.ShowMessage("RDP Filter -> UpdateRemoteCredential");
            pcpcsOut = pcpcsIn;

            pcpcsOut.clsidCredentialProvider = new Guid(Constants.CredentialProviderUID);

            this.rdp_login = true;

            return HResultValues.S_OK;
        }

After this, in SetSerialization

public int SetSerialization(ref _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION pcpcs)
        {
            Log.LogMethodCall();

            ShowInfo showInfo = new ShowInfo();
            showInfo.ShowMessage("SetSerialization");

            my_pcpcs = pcpcs;
            my_pcpcs.clsidCredentialProvider = Guid.Parse(Constants.CredentialProviderUID);

            this.rdp_login = true;

            return HResultValues.S_OK;
        }

After this, in GetCredentialCount 

public int GetCredentialCount(out uint pdwCount, out uint pdwDefault, out int pbAutoLogonWithDefault)
        {
            Log.LogMethodCall();            

            pdwCount = 1; // Credential tiles number
            pdwDefault = unchecked ((uint)0);
            //pbAutoLogonWithDefault = 0; // Try to auto-logon when all credential managers are enumerated (before the tile selection)

            if (this.rdp_login)
            {
                pbAutoLogonWithDefault = 1;
                ShowInfo showInfo = new ShowInfo();
                showInfo.ShowMessage("GetCredentialCount");
            }
            else
            {
                pbAutoLogonWithDefault = 0;
            }

            

            return HResultValues.S_OK;
        }

This will invoke GetSerialization

if (this.rdp_login)
            {
                showInfo.ShowMessage("GetSerialization for RDP");

                //pcpcs = my_pcpcs;

                pcpcs = new _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION();              

                pcpcs.clsidCredentialProvider = my_pcpcs.clsidCredentialProvider;
                pcpcs.rgbSerialization = my_pcpcs.rgbSerialization;
                pcpcs.cbSerialization = my_pcpcs.cbSerialization;

                //RetrieveNegotiateAuthPackage(out var authPackage);
                pcpcs.ulAuthenticationPackage = my_pcpcs.ulAuthenticationPackage;

                pcpgsr = _CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE.CPGSR_RETURN_CREDENTIAL_FINISHED;
                ppszOptionalStatusText = "RDP Success";
                pcpsiOptionalStatusIcon = _CREDENTIAL_PROVIDER_STATUS_ICON.CPSI_SUCCESS;
                
                
                return HResultValues.S_OK;

            }

After this, when we try to login via RDP (mstsc.exe) unable to unlock the workstation getting error as "Invalid Token"

**Comment by phaetto** [comment]
The serialization implemented in this project is not complete for all the paths.

You are probably looking to port an implementation of this: https://github.com/pgina/pgina/blob/f7cf2a074cf00432aa619478cedd8181b31f1680/pGina/src/CredentialProvider/SerializationHelpers.cpp#L103
