### ISSUE TITLE
CredUI field not shown

### ISSUE THREAD

**Issue by maskdroid02** [phaetto/windows-credentials-provider#3]
Hi,
I recently got interested in CredentialProvider and run across your genius .NET implementation for it. The interface did work in terms of being registered by Windows as a credential provider. However I encountered some issues in your demo
+ In _TestWindowsCredentialProviderTile.cs_ there are a small text and a submit button:
```
        public List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> CredentialProviderFieldDescriptorList = new List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> {
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SMALL_TEXT,
                dwFieldID = 0,
                pszLabel = "Rebootify Awesomeness",
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SUBMIT_BUTTON,
                dwFieldID = 1,
                pszLabel = "Login",
            }
        };
```
but the button did not appear in CredUI prompt.
![image](https://user-images.githubusercontent.com/32679558/34650185-2a12e91c-f3ef-11e7-9901-9107d592139d.png)
I tried to add an edit text but it wasn't shown either. Is it CredUI's limitation to only render the first text as a title and ignore everything else?

+ I went for  `_CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_LOGON` usage scenario and setup a dummy user account (including an username and a password) for a quick test. Then these infos was provided in `TestWindowsCredentialProviderTile.GetSerialization()` but LSA (LogonUI issued a _bad username or password_) refused to accept the credentials for that dummy user account. And also no button was rendered as in CredUI.
I was wondering if you had a concrete implementation for _Logon_ or _Unlock_ usage scenario which resembles Windows' default PasswordCredentialProvider.

Any help on this would be greatly appreciated.

**Comment by phaetto** [comment]
Hi @maskdroid02,
Thanks for your kind words and taking time to give your feedback.

For the first question you have the specs state (the xps file - I have a pdf in pull request #4):

> CPFT_SUBMIT_BUTTON
This field appears as a button on the credential tile. Pressing the button allows the user to submit their
credentials. There may be one and only one CPFT_SUBMIT_BUTTON for any credential tile. Unlike Logon
UI, which draws a special submit button in the tile layout, Credential UI hides this field and renders a
single submit button for all credentials. 

There is no special case for the text as far as I know, make sure you provide a unique dwFieldID for each. I get this when add one more:
![image](https://user-images.githubusercontent.com/1043755/34653793-9772651c-f3f1-11e7-918b-bed8830c2e80.png)

For the authentication problem that you have:
There could be so many reasons that this is not working. The main thing you have to consider is that this is definitely not a complete implementation - you can see one at pgina, a C++ implementation: https://github.com/pgina/pgina/blob/master/pGina/src/CredentialProvider/Credential.cpp#L257

To find out what is missing, I would start by creating a log of all the results of the p/invoke authentication methods under GetSerialization, and then continue from there.

I hope that helps! Cheers!
