### ISSUE TITLE
how can i use this credential on lock window

### ISSUE THREAD

**Issue by mohamed-sayed-0** [phaetto/windows-credentials-provider#6]
how can I show this credential provider as an option in for sign-in in windows 10

**Comment by sorset** [comment]
You can not!!! This is strictly forbidden except if you send mail request to special companion Microsoft mail address. If you are company owner and you have money you will get permission from Microsoft. At least you need to send mail request to share as much as you can company information and of course you need to prepare for bank transactions. For example dev access to Microsoft store for universal app development.

I move to Android and make unlock app for 10 minutes without any problem. Share free in Google store. Google not charged me as dev .

**Comment by phaetto** [comment]
Hey @MoAhmedSayed,

You can do that by changing 

                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_CREDUI:
                    return HResultValues.S_OK;


                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_LOGON:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_UNLOCK_WORKSTATION:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_CHANGE_PASSWORD:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_PLAP:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_INVALID:
                    return HResultValues.E_NOTIMPL;
                default:
                    return HResultValues.E_INVALIDARG;

to

                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_CREDUI:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_LOGON:
                    return HResultValues.S_OK;


                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_UNLOCK_WORKSTATION:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_CHANGE_PASSWORD:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_PLAP:
                case _CREDENTIAL_PROVIDER_USAGE_SCENARIO.CPUS_INVALID:
                    return HResultValues.E_NOTIMPL;
                default:
                    return HResultValues.E_INVALIDARG;

at TestWindowsCredentialProvider.cs

Remember to use a VM for testing - a problematic Credentials Manager would make your winlogon restart every time and lock you out.
