### ISSUE TITLE
Username & password field not shown

### ISSUE THREAD

**Issue by shanalalkasim** [phaetto/windows-credentials-provider#8]
Hi,
Thanks for this sample!!. However I encountered some issues in your demo.
I added username and password in loginUI

```
public List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> CredentialProviderFieldDescriptorList = new List<_CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR> {
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SMALL_TEXT,
                dwFieldID = 0,
                pszLabel = "Rebootify Awesomeness",
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_EDIT_TEXT,
                dwFieldID = 1,
                pszLabel = "Sample UserName",
                guidFieldType =Guid.Parse("da15bbe8-954sd-4fd3-b0f4-1fb5b90b174b")
                //GUID has 33 character so runtime error. This Guid get from https://docs.microsoft.com/en-us/windows/desktop/api/credentialprovider/ns-credentialprovider-credential_provider_field_descriptor
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_PASSWORD_TEXT,
                dwFieldID = 2,
                pszLabel = "Sample Password",
                guidFieldType =Guid.Parse("60624cfa-a477-47b1-8a8e-3a4a19981827")
            },
            new _CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
            {
                cpft = _CREDENTIAL_PROVIDER_FIELD_TYPE.CPFT_SUBMIT_BUTTON,
                dwFieldID = 3,
                pszLabel = "Login",
            }
        };
```
If i added a new field other than CPFT_SMALL_TEXT, then Rebootify option is not listing login UI(without guidFieldType  field).
I added guidFieldType  for user name(microsoft doc providing incorrect GuID) and password but still its not work. Also i trying without username field, only password (bcz username guidFieldType   is incorrect) but still the result is same Rebootify option is not listing login UI.

Also one more point, in GetSerialization method i need to use 3rdparty IAM service, is it possible. then how to i create  _CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION?

Any help on this would be greatly appreciated.

**Comment by graudouin** [comment]
Hi Phaetto. Does this work on Windows 7?

**Comment by phaetto** [comment]
Hey @graudouin,

Windows 7 support Credential Providers as per this link:
https://github.com/Microsoft/Windows-classic-samples/tree/3e987d98a074051dc9cd5c87431d162035f69a24/Samples/Win7Samples/security/credentialproviders

However I haven't tested this repo on it. The biggest risk is that Windows 7 might support a subset of the ICredentialProvider/ICredentialProviderCredential interfaces.

**Comment by graudouin** [comment]
Thank you very much

**Comment by phaetto** [comment]
Unfortunately I don't have time to look at this issue - feel free to open it again in case you still need some help with it.

**Comment by graudouin** [comment]
Hey there,

 

I am new to Github. the download of the link below does not seem to be available.

 

Best Regards

Graham Audouin
